"""Structured counselor-style question bank for engineering students."""

QUESTIONS = [
    {
        "id": "programming_interest",
        "section": "Programming",
        "text": "How much do you enjoy programming or building software?",
        "type": "scale",
        "min": 1,
        "max": 5,
        "labels": {1: "Not much", 5: "A lot"},
    },
    {
        "id": "programming_rating",
        "section": "Programming",
        "text": "How would you rate your current programming ability?",
        "type": "scale",
        "min": 1,
        "max": 5,
        "labels": {1: "Beginner", 5: "Strong"},
    },
    {
        "id": "debugging_patience",
        "section": "Programming",
        "text": "How comfortable are you debugging code for long stretches?",
        "type": "scale",
        "min": 1,
        "max": 5,
        "labels": {1: "Low patience", 5: "Very patient"},
    },
    {
        "id": "linear_algebra",
        "section": "Math",
        "text": "How comfortable are you with linear algebra?",
        "type": "scale",
        "min": 1,
        "max": 5,
        "labels": {1: "Uncomfortable", 5: "Very comfortable"},
    },
    {
        "id": "probability",
        "section": "Math",
        "text": "How comfortable are you with probability?",
        "type": "scale",
        "min": 1,
        "max": 5,
        "labels": {1: "Uncomfortable", 5: "Very comfortable"},
    },
    {
        "id": "statistics",
        "section": "Math",
        "text": "How comfortable are you with statistics?",
        "type": "scale",
        "min": 1,
        "max": 5,
        "labels": {1: "Uncomfortable", 5: "Very comfortable"},
    },
    {
        "id": "ai_interest",
        "section": "Interests",
        "text": "How interested are you in AI, machine learning, and model building?",
        "type": "scale",
        "min": 1,
        "max": 5,
        "labels": {1: "Low", 5: "High"},
    },
    {
        "id": "data_interest",
        "section": "Interests",
        "text": "How interested are you in finding insights from data?",
        "type": "scale",
        "min": 1,
        "max": 5,
        "labels": {1: "Low", 5: "High"},
    },
    {
        "id": "web_interest",
        "section": "Interests",
        "text": "How interested are you in web development and product features?",
        "type": "scale",
        "min": 1,
        "max": 5,
        "labels": {1: "Low", 5: "High"},
    },
    {
        "id": "cloud_interest",
        "section": "Interests",
        "text": "How interested are you in cloud infrastructure, automation, and deployments?",
        "type": "scale",
        "min": 1,
        "max": 5,
        "labels": {1: "Low", 5: "High"},
    },
    {
        "id": "cybersecurity_interest",
        "section": "Interests",
        "text": "How interested are you in cybersecurity, risk, and secure systems?",
        "type": "scale",
        "min": 1,
        "max": 5,
        "labels": {1: "Low", 5: "High"},
    },
    {
        "id": "testing_interest",
        "section": "Interests",
        "text": "How interested are you in testing, quality, and automation?",
        "type": "scale",
        "min": 1,
        "max": 5,
        "labels": {1: "Low", 5: "High"},
    },
    {
        "id": "business_interest",
        "section": "Interests",
        "text": "How interested are you in business problems, requirements, and stakeholder communication?",
        "type": "scale",
        "min": 1,
        "max": 5,
        "labels": {1: "Low", 5: "High"},
    },
    {
        "id": "uiux_interest",
        "section": "Interests",
        "text": "How interested are you in UI/UX design and user research?",
        "type": "scale",
        "min": 1,
        "max": 5,
        "labels": {1: "Low", 5: "High"},
    },
    {
        "id": "working_style",
        "section": "Working Style",
        "text": "Which working style feels most natural to you?",
        "type": "choice",
        "options": [
            "Deep technical problem solving",
            "Visual and creative design work",
            "Data exploration and reasoning",
            "System reliability and operations",
            "Communication, planning, and coordination",
            "Investigating risks and edge cases",
        ],
    },
    {
        "id": "project_preference",
        "section": "Working Style",
        "text": "What kind of project would you pick first?",
        "type": "choice",
        "options": [
            "Build an AI model or chatbot",
            "Analyze a dataset and present insights",
            "Create a full web application",
            "Design cloud deployment pipelines",
            "Automate test cases for an app",
            "Map user journeys and improve screens",
            "Secure an application and find vulnerabilities",
            "Gather requirements for a product team",
        ],
    },
    {
        "id": "career_goal",
        "section": "Career Goals",
        "text": "What is your most important early-career goal?",
        "type": "choice",
        "options": [
            "Get a software engineering role quickly",
            "Work on AI or advanced technology",
            "Use data to support decisions",
            "Build secure and reliable systems",
            "Blend technology with business communication",
            "Create user-friendly digital products",
        ],
    },
    {
        "id": "learning_commitment",
        "section": "Career Goals",
        "text": "How many focused hours per week can you commit for the next 3 months?",
        "type": "choice",
        "options": ["3-5 hours", "6-8 hours", "9-12 hours", "13+ hours"],
    },
]


def question_count() -> int:
    return len(QUESTIONS)
